# Generated by Django 2.1.5 on 2019-01-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='was_include_in_home',
            new_name='was_included_in_home',
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
